create table if not exists public.browser_price_observations (
  id bigint generated by default as identity primary key,
  run_id uuid not null unique,
  target_id text,
  retailer text not null,
  requested_url text not null,
  final_url text,
  observed_at timestamptz not null,
  status text not null check (status in ('ok','identifier_mismatch','price_not_found','blocked','navigation_error','error')),
  accepted boolean not null default false,
  http_status integer,
  page_title text,
  currency text not null default 'GBP',
  price numeric(12,2),
  price_text text,
  availability text,
  expected_sku text,
  expected_ean text,
  identifier_match boolean,
  identifiers jsonb not null default '{"sku":[],"ean":[],"mpn":[]}'::jsonb,
  price_candidates jsonb not null default '[]'::jsonb,
  screenshot_file text,
  duration_ms integer not null,
  error text,
  created_at timestamptz not null default now()
);

create index if not exists browser_price_observations_target_time_idx
  on public.browser_price_observations (target_id, observed_at desc);

create index if not exists browser_price_observations_retailer_time_idx
  on public.browser_price_observations (retailer, observed_at desc);

alter table public.browser_price_observations enable row level security;

comment on table public.browser_price_observations is
  'Raw browser evidence. Inserts are made only by the GitHub Actions service-role secret.';
